### ISSUE TITLE
Ignored group values

### ISSUE THREAD

**Issue by mdigger** [lmittmann/tint#3]
`slog.Group("rpc", slog.String("request", "test"))`

> `5:33PM INF call rpc= duration=161.792µs req=`

**Comment by FabianTe** [comment]
I tried looking into this (https://github.com/FabianTe/tint/commits/feat/grouped-attrs).

Adding support for grouped values seems to require adding some logic to `handler.appendAttr`. Have a look at the implementation of the text handler ([here](https://cs.opensource.google/go/x/exp/+/10a50721:slog/handler.go;l=467;drc=10a507213a2916eb81243cb95bcd7f5e70a771e1;bpv=1;bpt=1) and [here](https://cs.opensource.google/go/x/exp/+/10a50721:slog/handler.go;l=410;bpv=1;bpt=1))

The implementation makes use of a [`handleState` type](https://cs.opensource.google/go/x/exp/+/10a50721:slog/handler.go?q=symbol%3A%5Cbslog.handleState%5Cb%20case%3Ayes) which is not present int `tint`.

@lmittmann what do you think? I guess it could be useful to adopt `handleState`?

**Comment by telemachus** [comment]
As an alternative to `handleState`, take a look at [`withsupport` in jba's slog extras repository](https://github.com/jba/slog/tree/main/withsupport).

I'm using that as an internal package in a handler that I'm currently writing, and it works well. (The handler I have in mind isn't quite ready to make fully public, but here's [the current code as well as some tests for the groups](https://gist.github.com/telemachus/760af16c3bd8ff8f43d38af537cb652a).)

**Comment by FabianTe** [comment]
@lmittmann Nice! I have to admin I am a bit amazed about your simple solution 👍🏻
