### ISSUE TITLE
feat request: colorize the message

### ISSUE THREAD

**Issue by missedone** [lmittmann/tint#43]
@xy-planning-network has a nice feature on the forked repo: https://github.com/xy-planning-network/tint/commit/662ca545427ccb5267ee2dab1e49271d98da3c9c

looking forward to have this in tint

**Comment by lmittmann** [comment]
You can add custom coloring using the `ReplaceAttr` option or create/use a fork with this feature. 

The output format is opinionated and I want the API to stay small and close to the `slog.TextHandler`. There are many requests for small format changes. So far the `ReplaceAttr` option seems like a good middle ground.

**Comment by missedone** [comment]
`ReplaceAttr` doesn't tell the log level, so hard to colorize per level
