### ISSUE TITLE
Still colorize level when replaceAttr exist

### ISSUE THREAD

**Issue by advoretsky** [lmittmann/tint#53]
The main feature I went to use this module is colorizing log level. I have a custom replaceAttr in the my project, but still would like to see levels colorized

**Comment by lmittmann** [comment]
Can you please provide an example snipped of your `tint.Options` that shows the described behavior.

**Comment by lmittmann** [comment]
Will be closed until more info is provided by @advoretsky

**Comment by advoretsky** [comment]
Sorry for the delay. Here is my usage: ```
func NewConsoleHandler(w io.Writer, level slog.Leveler, contextHandlers []logging.ContextHandler) slog.Handler {
	return newCommonHandler(
	return newCommonHandler(
		slog.NewTextHandler(
		tint.NewHandler(
			w,
			w,
			&slog.HandlerOptions{
			&tint.Options{
				AddSource:   true,
				AddSource:   true,
				Level:       level,
				Level:       level,
				ReplaceAttr: handleAttrs,
				TimeFormat:  time.Kitchen,
			},
			},
		),
```
In the `handleAttrs` I do "color unrelated things" that I do both for json output in production and console output in dev.

**Comment by lmittmann** [comment]
Please provide something reproducible. Putting some ReplaceAttr does not break coloring per se.

**Comment by advoretsky** [comment]
Correct. The issue was I changed the type of the level attribute in my code. 
```
func handleAttrs(groups []string, a slog.Attr) slog.Attr {
	switch a.Key {
	case slog.LevelKey:
		return slog.String(a.Key, strings.ToLower(a.Value.String()))
	}
	return a
}
```
So the behavior depends on the type of the of the level attribute and doesn't handle situation when type is not AnyKind / slog.Level

please disregard the issue
