### ISSUE TITLE
Wrong colors somehow

### ISSUE THREAD

**Issue by TLINDEN** [lmittmann/tint#56]
Howdy,

first of all: thanks for the module, very handy!

I've got a little problem though: the colors are somewhat wrong, at least the output doesn't look like the screenshot here.

Sample code as I use the module in my code:
```go
package main

import (
	"io"
	"log/slog"
	"os"

	"github.com/lmittmann/tint"
)

func main() {
	os.Exit(Main(os.Stdout))
}

func Main(w io.Writer) int {
	logLevel := &slog.LevelVar{}

	opts := &tint.Options{
		Level: logLevel,
	}

	logLevel.Set(slog.LevelDebug)

	handler := tint.NewHandler(w, opts)
	debuglogger := slog.New(handler).With(
		slog.Group("program_info",
			slog.Int("pid", os.Getpid()),
		),
	)
	slog.SetDefault(debuglogger)

	slog.Info("info")
	slog.Warn("warn")
	slog.Error("err")
	slog.Debug("debug")

	return 0
}
```

This how the output looks like:

![slog-colors](https://github.com/lmittmann/tint/assets/1322812/2d4d932e-d3d4-4e50-b486-12d4ecb7f683)

The error color is correct, the others are just greyscale colors.

Do I something wrong, is there a bug or can I possibly customize the colors?

Thanks in advance,
Tom

**Comment by lmittmann** [comment]
Hi, since your output is colored I guess this is related to the color profile of your terminal. You can customize the coloring using `Options.ReplaceAttr` and returning a custom string with coloring codes for the level type (see https://github.com/lmittmann/tint/issues/32#issuecomment-1694252941)
