### ISSUE TITLE
Test TestReplaceAttr fails sometimes

### ISSUE THREAD

**Issue by jose-tim** [lmittmann/tint#60]
Each Log call internally performs a time.Now() call, so in case enough time passes on the testing machine, them will fail.

![imagen](https://github.com/lmittmann/tint/assets/152218193/83e20299-7308-44dc-8a11-a5096ece52a3)

My proposal is call to time.Now on each testcase, and force-set it to the time key of the log params:

![imagen](https://github.com/lmittmann/tint/assets/152218193/7745536b-2bb8-46a8-82b5-31b420c5aa99)

**Comment by lmittmann** [comment]
`tint` uses the env var `TZ=""` to set the time zone to UTC and the flag `-tags=faketime` to make `time.Now()` return the same constant value in tests.

See https://github.com/lmittmann/tint/blob/main/.github/workflows/go.yml#L33
