### ISSUE TITLE
Having an option to keep built-in attributes in the log 

### ISSUE THREAD

**Issue by YeminLi** [lmittmann/tint#65]
Hey, it would be great if there is an option that allows preserving built-in attributes (`time`, `level`, `msg`..) in the log.
So basically, instead of having logs like
```
2024-06-24T20:29:08Z INF this is a message key_1="1234" key_2=456
```
The log will looks like below with the new option.
```
time=2024-06-24T20:29:08Z level=INF msg="this is a message" key_1="1234" key_2=456
```

Let me know if this makes sense.
Maybe I can provide a PR if this looks ok.

**Comment by lmittmann** [comment]
That looks exactly like the format of the `slog.TextHandler`. Why not use that?

**Comment by YeminLi** [comment]
> That looks exactly like the format of the `slog.TextHandler`. Why not use that?

Yes, you are right!
However, I still want to have some color in the log so it's slightly more readable.
