### ISSUE TITLE
Enhancement for source attribute

### ISSUE THREAD

**Issue by M0hammadUsman** [lmittmann/tint#68]
Integrated Development Environments (IDEs) such as GoLand utilize relative file paths for referencing code lines. This functionality enhances the debugging process and facilitates efficient navigation through source files to locate specific lines of interest. 
e.g. Watch this video

 [![demo](https://github.com/user-attachments/assets/62a519dd-e011-420f-8c8e-f1b0efeb3b4c)](https://github.com/user-attachments/assets/f0f97391-00e6-41d7-9473-5602a8be2d3b)

this make it easy for debugging and and moving through files to find a line you are looking for

currently I'm doing something like this

```go
tintHandler := tint.NewHandler(os.Stderr, &tint.Options{
	AddSource: true,
	ReplaceAttr: func(groups []string, attr slog.Attr) slog.Attr {
		if attr.Key == slog.SourceKey {
			src := attr.Value.Any().(*slog.Source)
			return slog.Attr{
				Key:   attr.Key,
				Value: slog.AnyValue(fmt.Sprintf("%s:%d", path.Base(src.File), src.Line)),
			}
		}
		return attr
	},
})
slog.SetDefault(slog.New(tintHandler))
```
which logs in `file:line` format

![CustomSourceAttr](https://github.com/user-attachments/assets/bafcdd25-c902-457d-89a7-c77e1477de02)

We propose modifying this implementation to log source information using relative paths by default, following the format `./relative/filename:lineNumber`. Alternatively, we suggest incorporating a mechanism to allow users to specify their preferred source formatting method.

**Comment by lmittmann** [comment]
`src.File` contains the absolute path to the file. you can log that directly or make it relative to your workspace dir in `ReplaceAttr`.
