### ISSUE TITLE
Incorrect level handler

### ISSUE THREAD

**Issue by mdigger** [lmittmann/tint#7]
```golang
if h.level < slog.LevelDebug {
    h.level = defaultLevel
}
```

_[source code](https://github.com/lmittmann/tint/blob/b5e779188a505c99e2df2c416e50bdf874d2aee2/handler.go#LL52C2-L52C2)_

How can I set the **trace** logging level (`slog.LevelDebug-4') with such restrictions?

**Comment by lmittmann** [comment]
Fixed in `v0.1.2`. Since the default level is `Info` which is 0 not setting it at all is fine. Hopefully slog doesn't change the default level value.
