### ISSUE TITLE
The addSource path is incomplete

### ISSUE THREAD

**Issue by huabingli** [lmittmann/tint#75]
Using filepath.Base(dir) results in an incomplete project path.
![image](https://github.com/user-attachments/assets/5c73ba13-3932-48c1-ad68-98b734b8a3eb)

**Comment by lmittmann** [comment]
Can you give an example of what you are trying to do, and what you are seeing instead

**Comment by huabingli** [comment]
The directory structure of my project is like this, but the file path in the log is only `com\com_init.go`, which does not show the whole project path completely. I need to ask it to show `util\com\com_init.go`

I am sorry that this is the translation of the translator, may not be particularly correct description
```
├─api
│  ├─handler
│  ├─request
│  └─response
├─config
├─global
├─logs
├─middleware
├─model
│  └─enum
├─router
└─util
    └─com
```
![image](https://github.com/user-attachments/assets/a3ef420c-eadd-48f8-8674-e54cbdf4aedc)

**Comment by lmittmann** [comment]
you can customize the source using `ReplaceAttr` and use any info in `slog.Source`. See https://github.com/lmittmann/tint/issues/25#issuecomment-1676385341
