### ISSUE TITLE
Preserving tabs and newlines in attributes

### ISSUE THREAD

**Issue by nielskrijger** [lmittmann/tint#81]
Thank you for the clean and simple library! It has served us well since `log/slog` was released 👏 

Recently I tried to debug a SQL query which have a lot of `\t` and `\n`. Right now it'll show up as`query.sql="\nSELECT\n\t'List' AS type,\n\tlist.id,\n\tlist.title,\n\...`

I checked the code of this library; am I correct in thinking it's currently not possible to preserve tabs and newlines?

**Comment by lmittmann** [comment]
Yes, that is correct. `tint` uses `strconv.AppendQuote` if [needsQuoting](https://github.com/lmittmann/tint/blob/main/handler.go#L437-L447) is true. The behavior (escaping newline) is intended though, as `tint` tries to stay close to the logic of the `slog.TextHandler`.

#59 is related, as `strconv.AppendQuote` also escapes ANSI color codes, which is not wanted.

**Comment by iamralch** [comment]
@lmittmann is it possible to have an option that disable the default behavior?

**Comment by lmittmann** [comment]
> [@lmittmann](https://github.com/lmittmann) is it possible to have an option that disable the default behavior?

disable escaping new-line? I don't think it makes sense
